import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import Navigation from "@/components/Navigation";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "ProjectAnime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <div className="w-full h-px bg-gray-200 dark:bg-gray-700 transition-colors duration-200">
          {" "}
        </div>
        <div className="flex flex-1">
          <Navigation />
          <div className="flex-1 p-4 md:ml-24">
            {children}
            </div>
        </div>
      </body>
    </html>
  );
}
